language: php

php:
  - 7.0
  - 7.1

env:
  global:
    - TIKA_VERSION="1.15"
    - TIKA_PATH=$HOME/tika
    - EXT_SOLR_VERSION="6.1.0"
  matrix:
    - TYPO3_VERSION="~8.7.1"
    - TYPO3_VERSION="dev-master"

matrix:
  fast_finish: true
  allow_failures:
    - env: TYPO3_VERSION="dev-master"

before_install:
  - composer self-update
  - composer --version
  - composer global require fabpot/php-cs-fixer
  - composer global require namelesscoder/typo3-repository-client

install:
  - Build/Test/bootstrap.sh
script:
  - Build/Test/cibuild.sh
after_script:
  - Build/Release/ter_tag_uploader.sh
  - Build/Test/cleanup.sh

cache:
  directories:
    - $TIKA_PATH
    - $HOME/.composer/cache
