language: php

php:
  - 5.5
  - 5.6
  - 7.0

env:
  global:
    - TIKA_VERSION="1.12"
    - TIKA_PATH=$HOME/tika
  matrix:
    - TYPO3_VERSION="~7.6.0"
    - TYPO3_VERSION="dev-master"

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0

before_install:
  - composer self-update
  - composer --version

install:
  - Build/Test/bootstrap.sh
script:
  - Build/Test/cibuild.sh
after_script:
  - Build/Release/ter_tag_uploader.sh
  - Build/Test/cleanup.sh

cache:
  directories:
    - $TIKA_PATH
    - $HOME/.composer/cache
