language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - TIKA_VERSION="1.10"
    - TIKA_PATH=$HOME/tika
  matrix:
    - TYPO3_BRANCH=TYPO3_6-2
    - TYPO3_BRANCH=master

matrix:
  fast_finish: true
  exclude:
    - php: 5.3
      env: TYPO3_BRANCH=master
    - php: 5.4
      env: TYPO3_BRANCH=master

before_install:
  - composer self-update
  - composer --version

install: Tests/Build/bootstrap.sh
script: Tests/Build/cibuild.sh

cache:
  directories:
    - $TIKA_PATH
    - $HOME/.composer/cache
